NameError: name '__help__' is not defined
/cash return NameError: name '__help__' is not defined which was removed while implementing multi-language support in help menu.